# Generated by Django 5.1.4 on 2024-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Trabajador-RRHH', 'Empleado-RRHH'), ('Trabajador', 'Trabajador')], default='Trabajador', max_length=20),
        ),
    ]
